package appproto

import (
	"context"
	"encoding/binary"
	"math"
	"sync/atomic"
	"testing"
	"time"

	"github.com/srcfl/ftw/go/internal/control"
	"github.com/srcfl/ftw/go/internal/mpc"
)

// The geometry must match the app's src/lib/protocol/history.ts exactly —
// both ends compute tiles independently and meet on the etag. The reference
// values below were generated by running the app's own functions, so a
// mismatch here is a genuine wire break, not a test opinion.

func TestTileGeometryMatchesTheApp(t *testing.T) {
	if got := pointsPerTile(ResN5m); got != 144 {
		t.Fatalf("5m tile has %d points, the app says 144", got)
	}
	if got := pointsPerTile(ResN1h); got != 168 {
		t.Fatalf("1h tile has %d points, the app says 168", got)
	}

	// tileId: res/stride/tileIndex, epoch-aligned.
	at := int64(1_760_000_000_000)
	start := tileStartFor(ResN5m, at)
	if start%43_200_000 != 0 || start > at || at-start >= 43_200_000 {
		t.Fatalf("5m tile start %d is not the aligned tile containing %d", start, at)
	}
	if got, want := tileIDFor(ResN5m, 3, start), "5m/3/40740"; got != want {
		t.Fatalf("tileID = %q, want %q", got, want)
	}
}

func TestEtagMatchesTheAppByteForByte(t *testing.T) {
	// Values from the app's etagOf(), run on the same input.
	ascending := make([]byte, 16)
	for i := range ascending {
		ascending[i] = byte(i)
	}
	if got := etagOf(ascending); got != "c8fff215" {
		t.Fatalf("etag([0..15]) = %s, the app computes c8fff215", got)
	}
	if got := etagOf(nil); got != "811c9dc5" {
		t.Fatalf("etag(empty) = %s, the app computes 811c9dc5", got)
	}
}

func TestPlanHistoryQueryClampsAndStrides(t *testing.T) {
	// A day at 5m fits under 2000 points: two tiles, stride 1.
	day := planHistoryQuery(ResN5m, 1_760_000_000_000, 1_760_086_400_000, 2000)
	if day.res != ResN5m || day.stride != 1 {
		t.Fatalf("one day plan: res=%s stride=%d, want 5m stride 1", day.res, day.stride)
	}

	// Sixty days at 5m cannot fit even aggregated — the box clamps to the
	// coarser store rather than serving averages of averages.
	wide := planHistoryQuery(ResN5m, 1_760_000_000_000-60*86_400_000, 1_760_000_000_000, 2000)
	if wide.res != ResN1h {
		t.Fatalf("sixty day plan stayed on %s, want a clamp to 1h", wide.res)
	}

	// A tight cap first clamps to the coarser store — real data beats
	// averages of averages — and only then strides. A day under a 100-point
	// cap lands on 1h stride 2, exactly as the app's planQuery does.
	strided := planHistoryQuery(ResN5m, 1_760_000_000_000, 1_760_086_400_000, 100)
	if strided.res != ResN1h || strided.stride != 2 {
		t.Fatalf("100-point day: res=%s stride=%d, the app plans 1h stride 2", strided.res, strided.stride)
	}
	if pointsPerTile(strided.res)%strided.stride != 0 {
		t.Fatalf("stride %d does not divide the tile", strided.stride)
	}
	if strided.stepMs != resolutionStepMs[strided.res]*strided.stride {
		t.Fatalf("stepMs %d does not match stride %d at %s", strided.stepMs, strided.stride, strided.res)
	}
}

// fakeLedger serves one flat value per named series, on every bucket of the
// asked window — except holes, which it skips entirely, like the real ledger.
type fakeLedger struct {
	values map[string]float64
	holes  map[int64]bool
	calls  int
	err    error
}

func (f *fakeLedger) Window(
	_ context.Context, names []string, stepMs, fromMs, toMs int64,
) (map[string][]HistorySample, error) {
	f.calls++
	if f.err != nil {
		return nil, f.err
	}
	out := make(map[string][]HistorySample, len(names))
	for _, name := range names {
		value, ok := f.values[name]
		if !ok {
			continue
		}
		for at := fromMs; at < toMs; at += stepMs {
			if f.holes[at] {
				continue
			}
			out[name] = append(out[name], HistorySample{StartMs: at, W: value})
		}
	}
	return out, nil
}

func waitHistory(t *testing.T, h *Handler) {
	t.Helper()
	deadline := time.Now().Add(2 * time.Second)
	for time.Now().Before(deadline) {
		h.histMu.Lock()
		idle := !h.histRunning && h.histPending == nil
		h.histMu.Unlock()
		if idle {
			return
		}
		time.Sleep(time.Millisecond)
	}
	t.Fatal("history worker did not become idle")
}

func newHistoryRig(t *testing.T, ledger HistoryProvider) (*Handler, *recorder, *fakeClock) {
	t.Helper()
	clock := &fakeClock{uptimeMs: 60_000, now: time.UnixMilli(1_760_000_000_000)}
	box := &fakeBox{
		identity:     Identity{ID: "ftw-0001", Build: "test", TZ: "Europe/Stockholm"},
		mode:         control.ModePlannerPassiveArbitrage,
		snap:         Snapshot{Mode: control.ModePlannerPassiveArbitrage, DispatchBlockedBy: []string{}},
		observedMode: control.ModePlannerPassiveArbitrage,
		observedOK:   true,
	}
	rec := &recorder{}
	h, err := New(Config{
		Clock: clock, Site: box, Info: box, Modes: box, Plans: box,
		History: ledger,
		Codec:   testCodec{}, Sender: rec,
		Caller: ownerCaller(), Grants: newGrants(),
		SrcGrid: "meter.p1", SrcPV: "meter.p1", SrcBattery: "meter.p1",
		NewLeaseID: func() string { return "lease-test" },
	})
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	t.Cleanup(h.Close)
	subscribe(t, h, rec)
	return h, rec, clock
}

func histChunks(rec *recorder) []HistChunk {
	var out []HistChunk
	for _, f := range rec.frames {
		if f.env.T != MsgHistChunk {
			continue
		}
		var c HistChunk
		if err := Unmarshal(f.env.B, &c); err == nil {
			out = append(out, c)
		}
	}
	return out
}

func TestHistQueryServesTilesAndAnEnd(t *testing.T) {
	ledger := &fakeLedger{values: map[string]float64{"grid_w": 1200, "pv_w": -800}}
	h, rec, clock := newHistoryRig(t, ledger)

	from := clock.now.UnixMilli() - 6*3_600_000
	deliver(t, h, MsgHistQuery, ptrU32(9), HistQuery{
		Series: []string{"grid_w", "pv_w"},
		Res:    ResN5m,
		FromMs: from,
		ToMs:   clock.now.UnixMilli(),
	})
	waitHistory(t, h)
	wantCalls := len(planHistoryQuery(ResN5m, from, clock.now.UnixMilli(), defaultMaxPoints).tiles)
	if ledger.calls != wantCalls {
		t.Fatalf("provider called %d times for %d tiles and two series; want one read per tile", ledger.calls, wantCalls)
	}

	chunks := histChunks(rec)
	if len(chunks) == 0 {
		t.Fatalf("no chunks; frames: %s", rec.types())
	}
	end := rec.only(t, MsgHistEnd)
	if end.env.ID == nil || *end.env.ID != 9 {
		t.Fatalf("hist.end did not echo the request id: %v", end.env.ID)
	}
	e := body[HistEnd](t, end)
	if e.ResActual != ResN5m {
		t.Fatalf("resActual = %s, want 5m", e.ResActual)
	}
	if e.Gaps == nil {
		t.Fatal("gaps must be an empty list, never absent")
	}

	// The trailing tile contains "now" and must be marked partial.
	last := chunks[len(chunks)-1]
	if !last.Partial {
		t.Fatal("the tile containing now was not marked partial")
	}

	// Columns are int32 LE, one block per series, and a flat 1200 W series
	// must decode back to 1200 on a bucket inside the window.
	c := chunks[0]
	points := int(int64(len(c.Data)) / 4 / int64(len(c.Series)))
	idx := points - 1 // late in the first tile, safely inside the data
	grid := int32(binary.LittleEndian.Uint32(c.Data[idx*4:]))
	pv := int32(binary.LittleEndian.Uint32(c.Data[(points+idx)*4:]))
	if grid != 1200 || pv != -800 {
		t.Fatalf("decoded grid=%d pv=%d, want 1200 and -800", grid, pv)
	}
}

type cancelLedger struct {
	calls    atomic.Int32
	started  chan struct{}
	canceled chan struct{}
}

type stubbornLedger struct {
	started chan struct{}
	release chan struct{}
}

func (f *stubbornLedger) Window(
	_ context.Context, _ []string, _ int64, _, _ int64,
) (map[string][]HistorySample, error) {
	close(f.started)
	<-f.release
	return map[string][]HistorySample{}, nil
}

func (f *cancelLedger) Window(
	ctx context.Context, _ []string, _ int64, _, _ int64,
) (map[string][]HistorySample, error) {
	if f.calls.Add(1) == 1 {
		close(f.started)
		<-ctx.Done()
		close(f.canceled)
		return nil, ctx.Err()
	}
	return map[string][]HistorySample{}, nil
}

func TestHistoryDoesNotBlockFramesAndNewestQueryCancelsTheOldOne(t *testing.T) {
	ledger := &cancelLedger{started: make(chan struct{}), canceled: make(chan struct{})}
	h, rec, clock := newHistoryRig(t, ledger)
	from := clock.now.UnixMilli() - 3_600_000

	deliver(t, h, MsgHistQuery, ptrU32(20), HistQuery{
		Series: []string{"grid_w"}, Res: ResN5m, FromMs: from, ToMs: clock.now.UnixMilli(),
	})
	select {
	case <-ledger.started:
	case <-time.After(time.Second):
		t.Fatal("history provider did not start")
	}

	// The shared uplink reader can still dispatch another message while SQLite
	// history is waiting.
	deliver(t, h, MsgPlanGet, ptrU32(21), nil)
	if !rec.has(MsgPlan) {
		t.Fatal("history query blocked a later frame")
	}

	deliver(t, h, MsgHistQuery, ptrU32(22), HistQuery{
		Series: []string{"grid_w"}, Res: ResN5m, FromMs: from, ToMs: clock.now.UnixMilli(),
	})
	select {
	case <-ledger.canceled:
	case <-time.After(time.Second):
		t.Fatal("replacement did not cancel the old provider context")
	}
	waitHistory(t, h)

	var superseded, completed bool
	for _, f := range rec.snapshot() {
		switch f.env.T {
		case MsgError:
			if f.env.ID != nil && *f.env.ID == 20 {
				superseded = body[ErrorBody](t, f).Args["reason"] == "superseded"
			}
		case MsgHistEnd:
			completed = f.env.ID != nil && *f.env.ID == 22
		}
	}
	if !superseded || !completed {
		t.Fatalf("superseded=%v completed=%v; frames=%s", superseded, completed, rec.types())
	}
}

func TestEvictedQuerySupersedesAProviderThatIgnoresCancellation(t *testing.T) {
	ledger := &stubbornLedger{started: make(chan struct{}), release: make(chan struct{})}
	h, rec, clock := newHistoryRig(t, ledger)
	deliver(t, h, MsgHistQuery, ptrU32(30), HistQuery{
		Series: []string{"grid_w"}, Res: ResN5m,
		FromMs: clock.now.UnixMilli() - 3_600_000, ToMs: clock.now.UnixMilli(),
	})
	select {
	case <-ledger.started:
	case <-time.After(time.Second):
		t.Fatal("stubborn provider did not start")
	}

	// This valid window is wholly beyond retention and needs no provider read,
	// but it is still the newest query and must replace the active one.
	deliver(t, h, MsgHistQuery, ptrU32(31), HistQuery{
		Series: []string{"grid_w"}, Res: ResN5m,
		FromMs: clock.now.Add(-3 * 365 * 24 * time.Hour).UnixMilli(),
		ToMs:   clock.now.Add(-5 * 365 * 24 * time.Hour / 2).UnixMilli(),
	})
	close(ledger.release)
	waitHistory(t, h)

	var oldError, newEnd bool
	for _, f := range rec.snapshot() {
		if f.env.ID == nil {
			continue
		}
		switch *f.env.ID {
		case 30:
			if f.env.T == MsgHistChunk || f.env.T == MsgHistEnd {
				t.Fatalf("superseded query sent %s after its ignored cancellation", f.env.T)
			}
			if f.env.T == MsgError {
				oldError = body[ErrorBody](t, f).Args["reason"] == "superseded"
			}
		case 31:
			newEnd = f.env.T == MsgHistEnd
		}
	}
	if !oldError || !newEnd {
		t.Fatalf("oldError=%v newEnd=%v; frames=%s", oldError, newEnd, rec.types())
	}
}

func TestHistoryClampsPointsAndSkipsEvictedYears(t *testing.T) {
	ledger := &fakeLedger{values: map[string]float64{"grid_w": 500}}
	h, rec, clock := newHistoryRig(t, ledger)
	tooMany := int64(math.MaxInt64)
	from := clock.now.Add(-3 * 365 * 24 * time.Hour).UnixMilli()
	deliver(t, h, MsgHistQuery, ptrU32(23), HistQuery{
		Series: []string{"grid_w"}, Res: ResN5m, FromMs: from, ToMs: clock.now.UnixMilli(),
		MaxPoints: &tooMany,
	})
	waitHistory(t, h)

	chunks := histChunks(rec)
	if len(chunks) == 0 || len(chunks) > 106 {
		t.Fatalf("bounded two-year query returned %d tiles", len(chunks))
	}
	if ledger.calls != len(chunks) {
		t.Fatalf("provider reads=%d chunks=%d, want one per served tile", ledger.calls, len(chunks))
	}
	end := body[HistEnd](t, rec.only(t, MsgHistEnd))
	if len(end.Gaps) != 1 || end.Gaps[0].Reason != GapEvicted {
		t.Fatalf("gaps = %+v, want the skipped year marked evicted", end.Gaps)
	}
}

func TestHistoryRefusesDuplicateSeries(t *testing.T) {
	h, rec, clock := newHistoryRig(t, &fakeLedger{})
	deliver(t, h, MsgHistQuery, ptrU32(24), HistQuery{
		Series: []string{"grid_w", "grid_w"}, Res: ResN5m,
		FromMs: clock.now.UnixMilli() - 3_600_000, ToMs: clock.now.UnixMilli(),
	})
	if got := body[ErrorBody](t, rec.only(t, MsgError)); got.Code != ErrUnknownOp {
		t.Fatalf("duplicate series returned %s", got.Code)
	}
}

func TestUnknownHistorySeriesDegradesToMissing(t *testing.T) {
	h, rec, clock := newHistoryRig(t, &fakeLedger{values: map[string]float64{"grid_w": 500}})
	deliver(t, h, MsgHistQuery, ptrU32(25), HistQuery{
		Series: []string{"grid_w", "pv_w", "battery_w", "load_w", "future_w"}, Res: ResN5m,
		FromMs: clock.now.UnixMilli() - 3_600_000, ToMs: clock.now.UnixMilli(),
	})
	waitHistory(t, h)
	chunks := histChunks(rec)
	if len(chunks) == 0 {
		t.Fatal("unknown additive series refused the whole history query")
	}
	c := chunks[0]
	if len(c.Series) != 5 || c.Series[4] != "future_w" {
		t.Fatalf("series = %v, want the additive fifth column preserved", c.Series)
	}
	points := len(c.Data) / 4 / len(c.Series)
	for p := 0; p < points; p++ {
		off := (4*points + p) * 4
		if got := int32(binary.LittleEndian.Uint32(c.Data[off:])); got != math.MinInt32 {
			t.Fatalf("future series point %d = %d, want MISSING", p, got)
		}
	}
}

func BenchmarkBuildHistoryTileFourSeries(b *testing.B) {
	ledger := &fakeLedger{values: map[string]float64{
		"grid_w": 1200, "pv_w": -800, "battery_w": 300, "load_w": 1700,
	}}
	h := &Handler{cfg: Config{History: ledger}}
	start := int64(1_760_000_000_000)
	plan := planHistoryQuery(ResN5m, start, start+ResolutionTileSpanMs[ResN5m], defaultMaxPoints)
	series := []string{"grid_w", "pv_w", "battery_w", "load_w"}
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		if _, err := h.buildTile(context.Background(), series, plan, plan.tiles[0], start+2*ResolutionTileSpanMs[ResN5m]); err != nil {
			b.Fatal(err)
		}
	}
}

func TestHistQueryTurnsAbsentBucketsIntoMissing(t *testing.T) {
	holeAt := tileStartFor(ResN5m, 1_760_000_000_000-6*3_600_000)
	ledger := &fakeLedger{
		values: map[string]float64{"grid_w": 500},
		holes:  map[int64]bool{holeAt: true},
	}
	h, rec, clock := newHistoryRig(t, ledger)

	deliver(t, h, MsgHistQuery, ptrU32(2), HistQuery{
		Series: []string{"grid_w"},
		Res:    ResN5m,
		FromMs: clock.now.UnixMilli() - 6*3_600_000,
		ToMs:   clock.now.UnixMilli(),
	})
	waitHistory(t, h)

	c := histChunks(rec)[0]
	offset := (holeAt - c.StartMs) / c.StepMs
	got := int32(binary.LittleEndian.Uint32(c.Data[offset*4:]))
	if got != math.MinInt32 {
		t.Fatalf("a bucket the ledger never wrote decoded to %d, want MISSING", got)
	}
}

func TestHistQuerySkipsTilesTheAppAlreadyHolds(t *testing.T) {
	ledger := &fakeLedger{values: map[string]float64{"grid_w": 500}}
	h, rec, clock := newHistoryRig(t, ledger)

	from := clock.now.UnixMilli() - 18*3_600_000 // three tiles: two closed, one partial
	deliver(t, h, MsgHistQuery, ptrU32(3), HistQuery{
		Series: []string{"grid_w"}, Res: ResN5m, FromMs: from, ToMs: clock.now.UnixMilli(),
	})
	waitHistory(t, h)
	first := histChunks(rec)

	var have []HistTileRef
	for _, c := range first {
		if !c.Partial {
			have = append(have, HistTileRef{TileID: c.TileID, Etag: c.Etag})
		}
	}
	if len(have) == 0 {
		t.Fatal("test needs at least one closed tile")
	}

	rec.reset()
	deliver(t, h, MsgHistQuery, ptrU32(4), HistQuery{
		Series: []string{"grid_w"}, Res: ResN5m, FromMs: from, ToMs: clock.now.UnixMilli(),
		Have: have,
	})
	waitHistory(t, h)
	second := histChunks(rec)

	for _, c := range second {
		if c.Partial {
			continue
		}
		for _, ref := range have {
			if c.TileID == ref.TileID {
				t.Fatalf("tile %s was resent although the app holds it unchanged", c.TileID)
			}
		}
	}
	if !rec.has(MsgHistEnd) {
		t.Fatal("a fully cached query still ends with hist.end")
	}
}

func TestHistQueryWithoutAProviderSaysUnavailable(t *testing.T) {
	h, rec, clock := func() (*Handler, *recorder, *fakeClock) {
		h, _, rec, clock := newRig(t)
		subscribe(t, h, rec)
		return h, rec, clock
	}()
	_ = clock

	deliver(t, h, MsgHistQuery, ptrU32(5), HistQuery{
		Series: []string{"grid_w"}, Res: ResN5m, FromMs: 0, ToMs: 1,
	})

	e := rec.only(t, MsgError)
	if e.env.ID == nil || *e.env.ID != 5 {
		t.Fatal("the error is not addressed to the request that caused it")
	}
	b := body[ErrorBody](t, e)
	if b.Code != ErrUnavailable {
		t.Fatalf("code = %s, want %s", b.Code, ErrUnavailable)
	}
}

// The plan used to be the message that killed sessions: 193 optimizer slots
// encode past the largest bulk bucket, sendBulk errored, and the uplink
// dropped the session — which the app experienced as "the box hangs up
// whenever I open the plan". The fix truncates; this proves it.
func TestAnOversizedPlanIsTruncatedNotFatal(t *testing.T) {
	h, box, rec, clock := newRig(t)
	subscribe(t, h, rec)

	actions := make([]mpc.Action, 193)
	for i := range actions {
		actions[i] = mpc.Action{
			SlotStartMs: clock.now.UnixMilli() + int64(i)*900_000,
			SlotLenMin:  15,
			PriceOre:    115.27,
			BatteryW:    1067.98,
			GridW:       -516.65,
			Reason:      "absorb PV surplus",
		}
	}
	box.plan = &mpc.Plan{GeneratedAtMs: clock.now.UnixMilli(), Actions: actions}

	deliver(t, h, MsgPlanGet, ptrU32(7), nil)

	f := rec.only(t, MsgPlan)
	p := body[Plan](t, f)
	if len(p.Slots) >= 193 {
		t.Fatalf("%d slots went out; the full plan does not fit any bucket", len(p.Slots))
	}
	if len(p.Slots) < 96 {
		t.Fatalf("only %d slots survived; a day should fit", len(p.Slots))
	}
	// The nearest slots survive — the tail is what gets dropped.
	if p.Slots[0].StartMs != clock.now.UnixMilli() {
		t.Fatal("truncation dropped the head of the plan instead of the tail")
	}
}
